FEATURE: Allow exclusion of properties from replication
punktDe/nodereplicator pull request #10
Opened 2021-07-14 11:04 UTC by batabana

We use the NodeReplicator package in a project but needed to exclude specific properties from being replicated/snyched in other dimensions. As explained in the readme file, I've added a new config option to allow exactly this.
If properties are specified in this option we store their values before the `similarize()` and afterwards set them back to their original values.

2021-07-14 15:07 UTC, daniellienert requested changes

2021-07-14 15:07 UTC, daniellienert commented on Classes/Replicator/NodeReplicator.php
> +        if ($excludedPropertyValues) {
$excludedPropertyValues is neither `false` nor `true`, please use empty($excludedPropertyValues). An early return would reduce code complexity.

2021-07-14 15:07 UTC, daniellienert commented on Classes/Replicator/NodeReplicator.php
> +        if ($excludedProperties) {
$excludedPropertyValues is neither false nor true, please use empty($excludedPropertyValues). An early return would reduce code complexity.

2021-07-14 15:07 UTC, daniellienert commented on Readme.md
> +| replication.excludeProperties           | Exclude properties from replication                                             |
```suggestion
| replication.excludeProperties           | Do not update values of these properties in the target node                        |
```

2021-07-16 04:54 UTC, daniellienert approved these changes

2021-07-16 04:55 UTC, merged

2021-07-26 14:05 UTC, paavo commented
@batabana are you using `punktDe/nodereplicator` to replicate Document Nodes?
Just asking because you exclude Properties like Meta Tags in your sample...

2021-07-26 21:39 UTC, daniellienert commented
@paavo we do That in our project. Any issues with that?

2021-07-27 06:35 UTC, paavo commented
I just gave it a quick try and after some weird behaviours i saw only informations about "content nodes" in the Readme @daniellienert 
What i still remember:
- "speaking URL Paths" were not generated/replicated
- "flowpack/nodevariantselector" threw some JS-Errors and broke the backend

But i can give it another try..

2021-07-27 06:38 UTC, daniellienert commented
Just had a look - the URL path segment is also copied over. We do not use the node variant selector